version: '3.9'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:7.0
    container_name: productos_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: productos_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - productos_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/productos_db --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Servicio de la API Node.js
  api:
    build: .
    container_name: productos_api
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/productos_db?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - productos_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

   
volumes:
  mongodb_data:
    driver: local

networks:
  productos_network:
    driver: bridge
