###
GET HTTP://localhost:3000/api/productos HTTP/1.1

###
POST HTTP://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json


 
{
  "nombre": "Camisa ",
  "descripcion": "Camisa  de alta gama",
  "precio": 499.99,
  "categoria": "ropa",
  "stock": 5
}

###
GET HTTP://localhost:3000/api/productos/68987b08977777c900f2abd3 HTTP/1.1

###
PUT HTTP://localhost:3000/api/productos/68987957977777c900f2abc7 HTTP/1.1  
Content-Type: application/json


{
  "nombre": "Laptop Gaming Pro",
  "descripcion": "Laptop para gaming de alta gama con mejores especificaciones",
  "precio": 1499.99,
  "categoria": "electronica",
  "stock": 5
}

###
DELETE HTTP://localhost:3000/api/productos/689882cae8140abcee89b041 HTTP/1.1

